version: "3"
services:
 api-server:
  container_name: api-server
  image: cherryjubilee/api-server:latest
  ports:
    - "80:8000"
  depends_on:
    - db
  restart: always
  links:
      - db:db

 db:
   container_name: db
   image: mysql:latest
   ports:
     - "3306:3306"
   environment:
     MYSQL_ROOT_PASSWORD: 12345678
     MYSQL_DATABASE: survey_proj