version: "3"

networks:
  section3-net:
    driver: bridge

services:
  api-server:
    container_name: api-server
    image: cherryjubilee/api-server:1.11
    ports:
      - "80:8000"
    depends_on:
      - db
    restart: always
    links:
      - db:db
    networks:
      - section3-net
    volumes:
      - ./temp:/usr/src/app/temp
 
  metabase:
    container_name: metabase
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    volumes:
      - ./metabase-data:/metabase-data
    networks:
      - section3-net
    links:
      - db:db
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: survey_proj
    networks:
      - section3-net
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d