version: "3"

networks:
  section3-net:
    driver: bridge

services:
  api-server:
    container_name: api-server
    image: cherryjubilee/api-server:1.3
    ports:
      - "80:8000"
    depends_on:
      - db
    restart: always
    links:
        - db:db
    networks:
      - section3-net
    volumes:
      - ./:/usr/src/app/temp
 
  db:
    container_name: db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: survey_proj
    networks:
      - section3-net